apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-if220129
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/automind-2527/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DOTNET_USE_POLLING_FILE_WATCHER
              value: "1"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: student-if220129
spec:
  type: ClusterIP        # bleibt intern im Cluster
  selector:
    app: backend
  ports:
    - port: 5191         # Port im Cluster
      targetPort: 5191   # Port im Container

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: student-if220129
  annotations:
    kubernetes.io/ingress.class: nginx
    traefik.ingress.kubernetes.io/router.entrypoints: "https"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "http"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: if2201291.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 5191