apiVersion: apps/v1
kind: Deployment
metadata:
  name: automind-backend
  namespace: student-if220129
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automind-backend
  template:
    metadata:
      labels:
        app: automind-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: pitchpeak-api
          image: ghcr.io/automind-2527/backend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: automind-backend-svc
  namespace: student-if220129
spec:
  selector:
    app: automind-backend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP