name: Backend(DemoSyp) Docker (for LeoCloud)

env:
  ContainerName: backend        # Name of the (docker-)container
  SolutionPath: AutoMindBackend            # sub-directory of sln file location
  CloudNameSpace: student-if220129
  AppPrefix: 
  
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: andrejnedic
          password: ${{ secrets.GHCR_PAT }}
      - name: Show repo files
        run: |
          pwd
          ls -la
          ls -la AutoMindBackend || true
          ls -la Backend || true 
  
      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/andrejnedic/${{ env.ContainerName }}:latest

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} deployment ${{ env.AppPrefix }}

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} service ${{ env.AppPrefix }}-svc

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} ingress ${{ env.AppPrefix }}-ingress

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} pod -l app=${{ env.AppPrefix }}

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create -f ./Leocloud/deployment.yaml
